Trinium and Taranium Chains
GregTechCEu/gregicality pull request #597
Opened 2021-08-21 18:17 UTC by pablocnvs

This pr adds the trinium and taranium chains designed by me and Zalgo

2021-08-21 20:01 UTC, TechLord22 requested changes
Overall, these voltages are very punishing. I'd like to see them all brought to the loss-adjusted values of their tier.

2021-08-21 20:53 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/GARecipeMaps.java
> +            0, 2, 0, 6, 0, 2, 0, 6, new LargeRecipeBuilder(RecipeMaps.CENTRIFUGE_RECIPES))
Sadly no

2021-08-21 20:54 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        VACUUM_RECIPES.recipeBuilder()
I think it requires a recipe output iirc

2021-08-21 20:59 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/TriniumChain.java
> +        ELECTROLYZER_RECIPES.recipeBuilder().duration(210).EUt(500)
For an electrolysis?

2021-08-21 21:07 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        VACUUM_RECIPES.recipeBuilder()
Ok it doesn't

2021-08-28 21:52 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        MIXER_RECIPES.recipeBuilder()
it is, but it's the lowest tier. i'll check if it is doable without having taranium, and i also might reduce the amount of taranium for the UHV superconductor again

2021-08-28 22:55 UTC, pablocnvs commented
hmm, the calculations you gave seem to suggest that we might need to increase by a factor of 8 or so many of this outputs else it won't be too enjoyable

2021-08-29 19:11 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +                .fluidOutputs(FluorosilicicAcid.getFluid(1000))
the dangers of copy paste

2021-09-22 23:21 UTC, TechLord22 requested changes

2021-09-22 23:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +                .notConsumable(new IntCircuitIngredient(0))
We want to avoid circuit #0 from now on, since it's technically only there as a default value. Should change to circuit #1.

2021-09-22 23:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TriniumChain.java
> +        ELECTROLYZER_RECIPES.recipeBuilder().duration(175).EUt(32)
Energy usage should drop to 30EU/t.

2021-09-24 01:03 UTC, TechLord22 requested changes

2021-09-24 01:03 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +                .fluidInputs(Dimethoxyethane.getFluid(500))
What was the reason for this change? If it is for chemical balance, the recipe comment should be updated accordingly.

2021-09-24 01:03 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/SuperconductorsSMDChain.java
> +        // TiCl4 + 2 C3H4 + 2 C2H2 -> 2 HCl + (C5H5)2Cl2Ti
The recipe should be updated accordingly.

2021-09-24 07:26 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +                .fluidInputs(Dimethoxyethane.getFluid(500))
tbh, it wasn't for chemical balance, just making it less annoying, whilst still being consumed

2021-09-30 21:12 UTC, TechLord22 requested changes

2021-09-30 21:12 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/CosmicChain.java
> +        // 6 H2O + 2 HCl + 2 AgBF4 + 8 C6H5Na + 2C8H20NBr + 2 AgClO4 + 3 (C5H5)2Cl2Ti + 6 C10H7F2N -> 2AgCl + 2NaBr + 6H2ONaCl + [3 (C5H5)2(C10H6F2N)2Ti + 2 (C6H5)4NBF4 + 8 C2H5OH]
This needs to output 4 moles of AgCl in order to be chemically balanced.

2021-09-30 21:22 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/CosmicChain.java
> +        // 6 H2O + 2 HCl + 2 AgBF4 + 8 C6H5Na + 2C8H20NBr + 2 AgClO4 + 3 (C5H5)2Cl2Ti + 6 C10H7F2N -> 2AgCl + 2NaBr + 6H2ONaCl + [3 (C5H5)2(C10H6F2N)2Ti + 2 (C6H5)4NBF4 + 8 C2H5OH]
Is that the last thing?

2021-10-17 13:50 UTC, Pnc6lx commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +                .buildAndRegister();
in this chain, 20 Uncommon Residues use 20 O2F2 ( 40 F ) → 10 Oxidized Residues and 10 Heavy Oxidized Residues, → 4+4 Dilute Hydrofluoric Acid → 4HF ( 4 F ) 
36 F is gone, is it wrong?

2021-10-17 18:04 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +                .buildAndRegister();
can you review the taranium chain fully?
yes that is an oversight we didn't consider

2021-11-30 03:51 UTC, TechLord22 requested changes
Currently the Taranium Chain still uses too much stone. Without looping, it consumes `43200` Stone for `1.2` Taranium Dust. With looping, it is approximately `1.5` Taranium Dust. We should aim to divide the stone number significantly. 

In the recipe producing Tiny `InertResidues`, changing it to regular dust (and to a simple material), will reduce the stone dust cost to `4800`, which is a far more reasonable number.

The recipe for the Protonated Fullerene Sieving Matrix uses 1 Fine Carbon Nanotube Wire. Is it intended for the Saturated Matrix to produce 6 at a 95% chance, instead of 1?

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TriniumChain.java
> +        LARGE_MIXER_RECIPES.recipeBuilder().duration(210).EUt(262000)
This recipe should use `MIXER_RECIPES`.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TriniumChain.java
> +                .notConsumable(OreDictUnifier.get(gemChipped, Jasper))
I don't think the Jasper is needed here. It gates this recipe unnecessarily far (behind the void miner), when the UVA Halide Lamp serves as enough of a gate in my opinion.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static final SimpleDustMaterial SilverNitrate = new SimpleDustMaterial("silver_nitrate", 0xfdfdca, (short) 172, MaterialIconSet.SHINY, "AgNO3");
This is missing a translation in the lang file.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TriniumChain.java
> +                .inputs(Fluorocarborane.getItemStack(125))
I think this could be reduced to 25. It seems much more fair given the complexity of Fluorocarborane.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
Use `CENTRIFUGE_RECIPES` here.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
Use `CENTRIFUGE_RECIPES` here.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
Use `CENTRIFUGE_RECIPES` here.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
Use `CENTRIFUGE_RECIPES` here.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
Use `CENTRIFUGE_RECIPES` here.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        LARGE_CENTRIFUGE_RECIPES.recipeBuilder()
Use `CENTRIFUGE_RECIPES` here.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +                .EUt(32700)
I do worry about the power costs for this, given how slow the rest of the chain is. We may want to consider using `7680` (IV) instead. Additionally, regular fusion is probably more appropriate here, otherwise the material cost of taranium production may be too high for it to reasonable done.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        LARGE_MIXER_RECIPES.recipeBuilder()
Use `MIXER_RECIPES` here.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        LARGE_CHEMICAL_RECIPES.recipeBuilder()
Use `CHEMICAL_RECIPES` here.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        PLASMA_CONDENSER_RECIPES.recipeBuilder()
To be consistent with other plasma condenser recipes, this should input 100mB of Liquid Helium, and output 100mB of Helium.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +
A plasma condenser recipe is needed for turning Hydrogen Plasma into Hydrogen.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TriniumChain.java
> +                .output(PROTONATED_FULLERENE_SIEVING_MATRIX.getMetaItem())
This needs to be `getStackForm()` instead of `getMetaItem()`.

2021-11-30 03:51 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TriniumChain.java
> +        LARGE_CHEMICAL_RECIPES.recipeBuilder().duration(180).EUt(131000)
Use `CHEMICAL_RECIPES` here.

2021-11-30 22:36 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/TriniumChain.java
> +                .inputs(Fluorocarborane.getItemStack(125))
Hmm, i would need to modify the fluoridation reaction so that we don't get duping, and that reaction is already a bit on the finicky side

2021-11-30 23:18 UTC, TechLord22 requested changes

2021-11-30 23:18 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +                .fluidOutputs(TaraniumRichHelium4.getFluid(100))
The amounts of these fluids were fine before. I meant to say that an additional fluid input of `100mB Liquid Regular Helium` and an additional fluid output of  `100mB Regular Helium` should be added to the recipe.

2021-11-30 23:18 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +        PLASMA_CONDENSER_RECIPES.recipeBuilder()
This recipe should have an additional fluid input of `100mB Liquid Regular Helium` and an additional fluid output of `100mB Regular Helium`.

2021-11-30 23:18 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TriniumChain.java
> +                .inputs(Fluorocarborane.getItemStack(125))
I didn't realize it was used in another reaction in the form of the matrix. In that case I think it would be better left alone. If there are improvements you can make (without too much trouble) to the other reaction you mentioned, definitely make those though.

2021-11-30 23:18 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +                .EUToStart(100000000)
This can be increased to some number between 320M and 640M in order to make the recipe require T3 fusion.

2021-11-30 23:24 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> +                .fluidOutputs(TaraniumRichHelium4.getFluid(100))
Oh, sorry

2021-11-30 23:39 UTC, TechLord22 approved these changes
The current state of the PR is in a good place for me. If there are any chemistry improvements you'd like to make, please do. Otherwise I'd say this is good to merge.

2021-12-25 04:56 UTC, TechLord22 approved these changes

2022-02-04 08:20 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/TaraniumChain.java
> -        CHEMICAL_RECIPES.recipeBuilder()
Is this change meant for people to skip easier naquadah processing? You should do instead a shortcut from Fluoronaquadric to Naquadah, else this step is a bit 😩

2022-02-06 05:35 UTC, merged